wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.15
    is_jupyter_run: true
    python_version: 3.6.8
batch_size:
  desc: null
  value: 245.45994257525754
epochs:
  desc: null
  value: 601.4301083405974
learning_rate:
  desc: null
  value: 1.0708368968714952
